project:
  type: website
  output-dir: docs

website:
  title: "qtm350-quiz02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index.qmd
        text: "Life Expectancy and GDP per Capita"
      - href: life-gdp.qmd
        text: "Life Expectancy and Population"
      - href: life-population.qmd
        text: "Country Analysis"
      - href: country.qmd
      - about.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



